# Generated by Django 5.0.6 on 2024-06-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
