# Generated by Django 5.0.6 on 2024-06-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_mymodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='boolean_field',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='date_field',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='date_time_field',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='duration_field',
            field=models.DurationField(default=None),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='email_field',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='file_field',
            field=models.FileField(default=None, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='file_path_field',
            field=models.FilePathField(default=None, path='/path/to/files/'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='float_field',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='generic_ip_address_field',
            field=models.GenericIPAddressField(default=None),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='image_field',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='integer_field',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='text_field',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='time_field',
            field=models.TimeField(default=None),
        ),
    ]
