# Generated by Django 5.0.6 on 2024-06-08 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_mymodel_boolean_field_mymodel_date_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='boolean_field',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='date_field',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='date_time_field',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='duration_field',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='email_field',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='file_field',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='file_path_field',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='float_field',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='generic_ip_address_field',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='image_field',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='integer_field',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='text_field',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='time_field',
        ),
    ]
