# Generated by Django 5.0.6 on 2024-06-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_remove_mymodel_boolean_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='boolean_field',
            field=models.BooleanField(default=None),
        ),
    ]
