# Generated by Django 5.0.6 on 2024-06-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_mymodel_duration_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='email_field',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
