# Generated by Django 5.0.6 on 2024-06-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_mymodel_email_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='file_field',
            field=models.FileField(default=None, upload_to='files/'),
        ),
    ]
