# Generated by Django 5.0.6 on 2024-06-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_mymodel_file_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='file_path_field',
            field=models.FilePathField(default=None, path='/path/to/files/'),
        ),
    ]
