# Generated by Django 5.0.6 on 2024-06-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_mymodel_file_path_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='file_path_field',
            field=models.FilePathField(path='/path/to/files/'),
        ),
    ]
