# Generated by Django 5.0.6 on 2024-06-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_alter_mymodel_file_path_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='file_path_field',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='float_field',
            field=models.FloatField(default=None),
        ),
    ]
