# Generated by Django 5.0.6 on 2024-06-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_remove_mymodel_file_path_field_mymodel_float_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='generic_ip_address_field',
            field=models.GenericIPAddressField(default=None),
        ),
    ]
