# Generated by Django 5.0.6 on 2024-06-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_mymodel_generic_ip_address_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='image_field',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
