# Generated by Django 5.0.6 on 2024-06-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_mymodel_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='integer_field',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='text_field',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='time_field',
            field=models.TimeField(default=None),
        ),
    ]
