# Generated by Django 5.0.6 on 2024-06-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0016_mymodel_integer_field_mymodel_text_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='boolean_field',
        ),
    ]
